import re
from playwright.sync_api import Page, expect
def test_example(page: Page) -> None:
    page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers")
    page.get_by_role("link", name="PIM").click()
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("textbox", name="First Name").fill("nada")
    page.get_by_role("textbox", name="Middle Name").fill("moh")
    page.get_by_role("textbox", name="Last Name").fill("salem")
    page.get_by_role("textbox").nth(4).click()
    page.get_by_role("textbox").nth(4).fill("1111")
    page.locator(".oxd-switch-input").click()
    page.get_by_role("textbox").nth(5).click()
    page.get_by_role("textbox").nth(5).fill("nada moh")
    page.locator("input[type=\"password\"]").first.click()
    page.locator("input[type=\"password\"]").first.fill("0000a$m")
    page.locator("input[type=\"password\"]").nth(1).click()
    page.locator("input[type=\"password\"]").nth(1).fill("0000a$m")
    page.get_by_role("button", name="Save").click()
    page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/193")
    # enter employee information 
    page.locator("form").filter(has_text="Employee Full NameEmployee").get_by_role("button").click()
    page.locator("form").filter(has_text="Employee Full NameEmployee").get_by_role("button").click()
    page.locator("div:nth-child(2) > div > .oxd-input-group > div:nth-child(2) > .oxd-input").click()
    page.locator(".oxd-input.oxd-input--focus").fill("555555")
    page.locator(".oxd-icon.bi-calendar").first.click()
    page.get_by_text("19").click()
    page.locator(".oxd-icon.bi-caret-down-fill.oxd-select-text--arrow").first.click()
    page.get_by_role("option", name="Afghan").click()
    page.locator("div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon").click()
    page.get_by_role("option", name="Single").click()
    page.locator("div:nth-child(5) > div:nth-child(2) > div > .oxd-input-group > div:nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-icon").click()
    page.get_by_text("12").click()
    page.get_by_text("Female").click()
    page.locator("form").filter(has_text="Employee Full NameEmployee").get_by_role("button").click()
    page.get_by_role("link", name="Add Employee").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("link", name="Employee List").click()
    expect(page.get_by_role("link", name="Employee List")).to_be_visible()
    page.get_by_role("textbox", name="Type for hints...").first.click()
    page.get_by_role("textbox", name="Type for hints...").first.fill("nada")
    page.get_by_role("textbox").nth(2).click()
    page.get_by_role("textbox").nth(2).fill("1111")
    page.get_by_role("button", name="Search").click()
    expect(page.get_by_text("(1) Record Found")).to_be_visible()
    expect(page.get_by_role("table")).to_match_aria_snapshot("- text: nada moh")
    page.get_by_text("nada moh").click()
